name: Continuous deployment
on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. '0.9.1', 'latest')
        version: 'latest'
    - name: Build
      run: |
        cp .gh-pages.env .env
        npm install
        npm run build
    - name: Package
      shell: bash
      run: |
        tar czvf target/sqler.tar.gz dist
        zip -r target/sqler.zip dist
        shasum -a 256 target/sqler.tar.gz > target/sqler.tar.gz.sha256
        shasum -a 256 target/sqler.zip > target/sqler.zip.sha256
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/sqler.tar.gz
          target/sqler.tar.gz.sha256
          target/sqler.zip
          target/sqler.zip.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy demo
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: dist
        clean: true